Uygulama03/Departmanlar/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace Departmanlar.Models
{
    public class Context:DbContext
    {
        public Context(DbContextOptions options) : base(options)
        {
        }
        public DbSet<departmanlar> departmanlars { get; set; }
        public DbSet<personel> personels { get; set; }
    }
}

Uygulama03/Departmanlar/Models/departmanlar.cs
using System.ComponentModel.DataAnnotations;

namespace Departmanlar.Models
{
    public class departmanlar
    {
        [Key]
        public int ID { get; set; }
        public string departmanAd { get; set; }
        public List<personel> personel { get; set;}
    }
}

Uygulama03/Departmanlar/Models/personel.cs
using System.ComponentModel.DataAnnotations;

namespace Departmanlar.Models
{
    public class personel
    {
        [Key]
        public int perId { get; set; }
        public string perAd { get; set; }
        public string perSoyad { get; set; }
        public string perSehir { get; set; }
        //nullable: true, false geliyor true yapınca hata düzeliyor
        public departmanlar departmanlars { get; set; }

    }
}

Uygulama03/Departmanlar/Controllers/HomeController.cs
using Departmanlar.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Departmanlar.Controllers
{
    public class HomeController : Controller
    {
        private readonly Context _context;

        public HomeController(Context contexts)
        {
            _context = contexts;
        }

        public IActionResult Index()
        {
            var degerler = _context.personels.ToList();
            return View(degerler);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Uygulama03/Departmanlar/Controllers/departController.cs
using Microsoft.AspNetCore.Mvc;
using Departmanlar.Models;
using System;

namespace Departmanlar.Controllers
{
    public class departController : Controller
    {
        //veri tabanı çekme
        private readonly Context _context;

        public departController(Context context)
        {
            _context = context;
        }
        //bitiş
        public IActionResult Index()
        {
            var degerler = _context.departmanlars.ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniDepartman()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniDepartman(departmanlar d)
        {
            _context.Add(d);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartSil(int id)
        {
            var dep = _context.departmanlars.Find(id);
            _context.departmanlars.Remove(dep);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartGetir(int id)
        {
            var dep = _context.departmanlars.Find(id);
            return View("DepartGetir", dep);
        }
        public IActionResult DepartmanGuncelle(departmanlar d)
        {
            var dep = _context.departmanlars.Find(d.ID);
            dep.departmanAd = d.departmanAd;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Uygulama03/Departmanlar/Views/Home/Index.cshtml
@using Departmanlar.Models;
@model List<personel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div>
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>ADI</th>
            <th>SOYAD</th>
            <th>SEHIR</th>
        </tr>
            @foreach (var x in Model)
            {
            <tr>
                <td>@x.perId</td>
                <td>@x.perAd</td>
                <td>@x.perSoyad</td>
                <td>@x.perSehir</td>
            </tr>

            }
    </table>
</div>

Uygulama03/Departmanlar/Views/Shared/_TextLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
body {
  margin: 0;
  font-family: "Lato", sans-serif;
}

.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}
 
.sidebar a.active {
  background-color: #04AA6D;
  color: white;
}

.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

div.content {
  margin-left: 200px;
  padding: 1px 16px; 
  height: 1000px;
}
</style>
</head>
<body>

<div class="sidebar">
  <h1 style="padding:0 15px">Menüler</h1>
  <a class="active" asp-controller="depart" asp-action="Index">Departmanlar</a>
  <a href="#news">Personeller</a>
  <a href="#contact">Hakkımızda</a>
  <a href="#about">Çıkış</a>
</div>
    
<div class="content">

    @RenderBody()
</div>

</body>
</html>

Uygulama03/Departmanlar/Views/depart/DepartGetir.cshtml
@model Departmanlar.Models.departmanlar;
@{
    ViewData["Title"] = "DepartGetir";
    Layout = "~/Views/Shared/_TextLayout.cshtml";
}


<h1>Departman Güncelle</h1>
<hr />
@using (Html.BeginForm("DepartmanGuncelle","depart",FormMethod.Post))
{
    <b>Departman ID</b>
    @Html.TextBoxFor(x => x.ID, new{@class = "form-control" })
    <br />
    <b>Departman Ad1</b>
    @Html.TextBoxFor(x => x.departmanAd, new{@class = "form-control" })
    <br />
    <button class="btn btn-info">Departman Ekle</button>
}

Uygulama03/Departmanlar/Views/depart/Index.cshtml
@using Departmanlar.Models;
@model List<departmanlar>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TextLayout.cshtml";
}
<h1>Departmanlar</h1>
<hr />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

        @foreach (var x in Model)
        {
        <tr>
            <td>@x.ID </td>
            <td>@x.departmanAd</td>
            <td><a href="/depart/DepartSil/@x.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/depart/DepartGetir/@x.ID" class="btn btn-success">Güncelle</a></td>
            <td><a href="#" class="btn btn-default" style="background-color:#dee61d">Detaylar</a></td>
        </tr>
        }
    
</table>
<a asp-controller="depart" asp-action="YeniDepartman" class="btn btn-primary">Yeni Depart</a>

Uygulama03/Departmanlar/Views/depart/YeniDepartman.cshtml
@{
    ViewData["Title"] = "YeniDepartman";
    Layout = "~/Views/Shared/_TextLayout.cshtml";
}

<h1>YeniDepartman</h1>
<hr />

<form method="post"> 
    <div class="mb-3">
        <label>Departman Adı:</label>
        <input name="departmanAd" class="form-control" />
    </div>
    <button class="btn btn-info">Departman Ekle</button>

</form>